### ISSUE TITLE
Has mtbench_plus golden answer?

### ISSUE THREAD

**Issue by lightislost** [LuJunru/MemoChat#1]

**Comment by LuJunru** [comment]
No. Similar to [MT-Bench](https://github.com/lm-sys/FastChat/blob/main/fastchat/llm_judge/data/mt_bench/question.jsonl), when evaluate on [MT-Bench-Plus](https://huggingface.co/datasets/Junrulu/MT-Bench-Plus), we directly ask GPT-4 to give a score. This is marking schema not pairwise or ranking.
